In [3]:
import pandas as pd
import numpy as np

In [32]:
class Percepton:
    
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4 # small values
        training = eta is not None and epochs is not None
        if training:
            self.eta = eta 
            self.epochs = epochs
            
    def _z_outcome(self, x_with_bias, weights):
        return np.dot(x_with_bias, weights)
    
    def activation_function(self, z):
        return np.where(z > 0, 1, 0)
    
    def fit(self, X, y):
        self.X_train = X
        self.Y_train = y
            
        X_with_bias = np.c_[self.X_train, -np.ones((len(self.X_train), 1))]
        print('X_with bias: ', X_with_bias)
        
        for epoch in range(self.epochs):
            print('--'*10)
            print('for epoch >> {0}'.format(epoch))
            print('--'*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            
            self.error = y - y_hat
            print('Error -->', self.error)
            
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"updated weights after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
            print("##"*10)
            
    
    def predict(self, X_test):
        X_with_bias = np.c_[X_test, -np.ones((len(X_test), 1))]
        z = self._z_outcome(X_with_bias)
        return self.activation_function(z)
    
    def total_loss(self):
        total_loss = np.sum(self.error)
        print(f"\ntotal loss: {total_loss}\n")
        return total_loss

In [36]:
def return_x_y(df):
    X = df.drop('y', axis=1)
    y = df.y
    return X, y

In [37]:
AND = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,0,0,1]
}

df_and = pd.DataFrame(AND)
X, y = return_x_y(df_and)

In [39]:
X, y

(   x1  x2
 0   0   0
 1   0   1
 2   1   0
 3   1   1,
 0    0
 1    0
 2    0
 3    1
 Name: y, dtype: int64)

In [40]:
X, y = prepare_data(df_AND)

ETA = 0.1 # 0 and 1
EPOCHS = 10

model_and = Percepton(eta=ETA, epochs=EPOCHS)
model_and.fit(X, y)

_ = model_and.total_loss()

X_with bias:  [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 0
--------------------
predicted value after forward pass: 
[1 1 1 0]
Error --> 0   -1
1   -1
2   -1
3    1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[-4.48861482e-05 -7.08974477e-05  1.99890154e-01]
####################
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 0 0 0]
Error --> 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[0.09995511 0.0999291  0.09989015]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[0 1 1 1]
Error --> 0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[-4.48861482e-05 -7.08974477e-05  2.99890154e-01]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 0 0 0]
Error --> 0    0
1    0

In [43]:
OR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,1]
}

In [45]:
df_or = pd.DataFrame(OR)
X_or, Y_or = return_x_y(df_or)

In [47]:
percepton_or = Percepton(eta=0.1, epochs=10)
percepton_or.fit(X_or, Y_or)

X_with bias:  [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 0
--------------------
predicted value after forward pass: 
[0 0 1 0]
Error --> 0    0
1    1
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 0.10005872  0.19986413 -0.19996165]
####################
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[1 1 1 1]
Error --> 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 0.10005872  0.19986413 -0.09996165]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
Error --> 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[1.00058720e-01 1.99864130e-01 3.83468014e-05]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 1 1 1]
Error --> 0    0
1    0
2    0
3   